### ISSUE TITLE
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 139 and stderr ""

### ISSUE THREAD

**Issue by jcope2013** [codeclimate/codeclimate-eslint#1]
followed instructions everything set up, when i run codeclimate analyze this is what happens

```
codeclimate analyze
Starting analysis
Running eslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 139 and stderr ""
```

any idea of how to debug futher?

**Comment by liamdawson** [comment]
I have also experienced this issue.

**Comment by pbrisbin** [comment]
Hi, from what I can tell, this (and another I've seen, status 138) are out-of-memory scenarios.

Are these large repos you're analyzing? If so, could you try cutting down the number of source files via `exclude_paths`?

**Comment by liamdawson** [comment]
I'm unsure why, but `exclude_paths` doesn't seem to work for me. My `db` folder still gets analysed by Rubocop. ESlint is probably going through all of the `bower_components` and `node_modules` :frowning:

**Comment by pbrisbin** [comment]
Can I see your codeclimate.yml? Specifically, I'm thinking `exclude_paths: db` won't work, and you need `exclude_paths: "db/**/*`. If that's the case, we should improve the docs in this regard.

**Comment by liamdawson** [comment]
I don't have the .codeclimate.yml file any more, unfortunately, and I never committed it because I didn't want to share it unless I had it working. I don't believe I used quotes around the path (like http://docs.codeclimate.com/article/289-configuring-your-repository-via-codeclimate-yml shows), if that has any relevance. I definitely did use the `**/*` pattern..

**Comment by tim-evans** [comment]
I'm running to this as well. It seems that `exclude_paths` aren't being respected by eslint (possibly due to different formats). I'm running this in an ember app, and had to remove `tmp`, `node_modules`, and `bower_components` to get `codeclimate analyze` to run.

**Comment by GordonDiggs** [comment]
@tim-evans what version of the CLI are you running? You can find that by running `codeclimate version`

**Comment by tim-evans** [comment]
@GordonDiggs 0.0.25

**Comment by GordonDiggs** [comment]
@tim-evans thanks - can you post the `.codeclimate.yml` file you are using?

**Comment by tim-evans** [comment]
Sure!

```yml
---
engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "app/**"
  - "addon/**"
  - "blueprints/**"
exclude_paths:
- config/**
- dist/**
- vendor/**
- node_modules/**
- bower_components/**
- tmp/**
```

**Comment by tim-evans** [comment]
The repository that I'm working on is: https://github.com/paddle8/ember-plupload

If you npm install and bower install, then try to run codeclimate analyze, the problem should appear.

**Comment by GordonDiggs** [comment]
https://github.com/paddle8/ember-plupload/pull/31

**Comment by tim-evans** [comment]
Thanks @GordonDiggs I'm working through this with @ABaldwinHunter right now and we're trying to ignore `blueprints/file-filter/files/app/file-filters/__name__.js` from analysis.

We've added the full path to `.codeclimate.yml`, but couldn't get rid of the warning. It seems like patterns in the `exclude_paths` aren't being respected by eslint.

**Comment by GordonDiggs** [comment]
@tim-evans I just pushed a new version of the image that changes the way we handle exclude patterns - is it better after you update?

**Comment by tim-evans** [comment]
@GordonDiggs still having trouble. Running `codeclimate analyze` on the addon repo after calling bower install / npm install still takes a long time.

I'm running codeclimate v 0.1.5 now.

**Comment by elwayman02** [comment]
I'm running into this issue as well, @GordonDiggs @tim-evans.  Would love a solution!  I'm on codeclimate 0.2.8 running the following config:

```
---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: false
  fixme:
    enabled: true
  watson:
    enabled: true
ratings:
  paths:
  - "app/**"
exclude_paths:
- bower_components/**/*
- dist/**/*
- node_modules/**/*
- tests/**/*
- tmp/**/*
- vendor/**/*
```

The project is an Ember 1.12 app w/ over 18,000 lines of code across 200+ files.
