### ISSUE TITLE
Definition for rule 'react/jsx-filename-extension' was not found

### ISSUE THREAD

**Issue by BenSwennen** [codeclimate/codeclimate-eslint#129]
I'm getting the following issues on codeclimate.com:

`Definition for rule 'react/jsx-filename-extension' was not found`

This rule is defined in eslint-plugin-react, which is supported by codeclimate eslint.

Here is my .eslintrc
```
{
  "extends": "airbnb",
  "rules": {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
    "quotes": [1, "double"]
  },
  "env": {
    "browser": true,
    "node": true,
    "jasmine": true
  },
  "plugins": [
    "react",
    "import",
    "jsx-a11y",
  ],
}
```

And my .codeclimate.yml
```
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-2" # leaving this line out does not make any difference
  fixme:
    enabled: true
ratings:
   paths:
   - "**.js"
   - "**.jsx"
exclude_paths: []
```
Am I doing something wrong?
