### ISSUE TITLE
eslint-plugin-import resolvers

### ISSUE THREAD

**Issue by gilbarbara** [codeclimate/codeclimate-eslint#143]
Hello!

Do you plan to add `eslint-plugin-import` resolvers for webpack (and node)?
It will be awesome since this plugin needs to resolve webpack aliases and modules for a complete analysis.

I'm almost disabling it completely since my apps rely on these features.
```
    checks:
      import/no-duplicates:
        enabled: false
      import/no-extraneous-dependencies:
        enabled: false
      import/no-named-as-default-member:
        enabled: false
      import/no-unresolved:
        enabled: false
```
Thanks
