### ISSUE TITLE
Error when running analyze

### ISSUE THREAD

**Issue by faun** [codeclimate/codeclimate-eslint#16]
When running `codeclimate analyze`, I get the following error:

``` console
Starting analysis
Running rubocop: Done!
Running coffeelint: Done!
Running eslint: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr "module.js:338\n    throw err;\n          ^\nError: Cannot find module 'eslint-plugin-nodeca'\n    at Function.Module._resolveFilename (module.js:3
36:15)\n    at Function.Module._load (module.js:278:25)\n    at Module.require (module.js:365:17)\n    at require (module.js:384:17)\n    at /usr/src/app/node_modules/eslint/lib/cli-engine.js:107:26\n    at Array.forEach (native)\n    at
loadPlugins (/usr/src/app/node_modules/eslint/lib/cli-engine.js:98:21)\n    at processFile (/usr/src/app/node_modules/eslint/lib/cli-engine.js:179:5)\n    at /usr/src/app/node_modules/eslint/lib/cli-engine.js:332:26\n    at /usr/src/app/n
ode_modules/eslint/lib/util/traverse.js:61:17\n"
```

Here's my `.codeclimate.yml`:

```yaml
---
engines:
  rubocop:
    enabled: true
  coffeelint:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: true
  fixme:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- db/**/*
- node_modules/**/*
- spec/**/*
- vendor/**/*
```

Do you have any suggestions on how to fix this?
