### ISSUE TITLE
Definition for rule 'react/jsx-filename-extension' was not found

### ISSUE THREAD

**Issue by davegri** [codeclimate/codeclimate-eslint#167]
How do I solve this?

My YML:
```
engines:
  eslint:
    enabled: true
  apexmetrics:
    enabled: true
    checks:
      AvoidLogicInTrigger:
        enabled: false
languages:
  JavaScript: true
ratings:
  paths:
    - "**.js"
    - "**.cls"
    - "**.trigger"
exclude_paths:
  - "tests/*"
  - "sfserver/app.js"
  - "sfserver/websocket/websocket.js"
  - "js_source/static/*"
```

**Comment by wfleming** [comment]
Hi @davegri,

The configuration here is using using ESLint version 1, which we currently have pinned to an older version of the `eslint-plugin-react` package, and that older version does not support this rule. I would suggest updating to use ESLint 3, which we have setup to use a newer version of the react plugin which supports this rule, and also may be helpful to you with newer built-in ESLint rules as well.

To use ESLint 3, you'll want to adjust the ESLint part of  your `.codeclimate.yml` to match this:

```yaml
eslint:
  channel: eslint-3
  enabled: true
```

If it's important to you to continue using ESLint 1, please let us know.
