### ISSUE TITLE
`ignore_warnings: false` behaves not as expected

### ISSUE THREAD

**Issue by GProst** [codeclimate/codeclimate-eslint#240]
When I write
```yaml
eslint:
    enabled: true
    config:
      ignore_warnings: false
```
I expect `eslint` engine to **NOT** ignore warnings. But it ignores them.
It only works correct if I completely cut `ignore_warnings` line out.
