### ISSUE TITLE
Not pulling from `eslint:recommended`

### ISSUE THREAD

**Issue by kyleholzinger** [codeclimate/codeclimate-eslint#246]
Recently I noticed that on codeclimate, some of the rules in `eslint:recommended` ruleset are not enabled. Is there any special config that I have to enable to get this to work? Specifically, I saw that the `no-inner-declarations` rule was ignored.

**Comment by dblandin** [comment]
@kyleholzinger Do you have `"extends": "eslint:recommended"` in your ESLint config?

If you don't have an ESLint configuration file within your repo, we use this as the inferred configuration, which does not extend from `eslint:recommended`: https://github.com/codeclimate/codeclimate/blob/master/config/eslint/.eslintrc.yml

**Comment by kyleholzinger** [comment]
Yeah, we have a `.eslintrc.json` file in our repo @dblandin

**Comment by kyleholzinger** [comment]
```json
// .eslintrc.json
{
  "env": {
    "browser": true,
    "es6": true
  },
  "plugins": ["mocha"],
  "extends": "eslint:recommended",
  "rules": {
    // all the other rules here
  }
}
```
```yml
# .codeclimate.yml
---
engines:
  eslint:
    enabled: true
    channel: "eslint-3"
ratings:
  paths:
  - "**.js"
```
