### ISSUE TITLE
Add config option to disable batch sanitization 

### ISSUE THREAD

**Issue by GordonDiggs** [codeclimate/codeclimate-eslint#289]
We sanitize a batch [here](https://github.com/codeclimate/codeclimate-eslint/blob/3edd7677c113d62d55a385f07b056301bb4aa591/bin/eslint.js#L196), which excludes minified files. For repos that want to disable this feature, we should support the following configuration in a `.codeclimate.yml` file:

```yml
engines:
  eslint:
    enabled: true
    config:
      sanitize_batch: false
```

This option should default to true
