### ISSUE TITLE
EngineFailure EACCESS permission denied (X)Ubuntu 14.04

### ISSUE THREAD

**Issue by bdunn313** [codeclimate/codeclimate-eslint#3]
I'm getting a similar result to issue #1 (engine failure), however I get a bit more robust error message:

```
error: (CC::Analyzer::Engine::EngineFailure) engine eslint failed with status 1 and stderr "fs.js:761
return binding.readdir(pathModule._makeLong(path));
    Error: EACCES, permission denied '/code'
        at Error (native)
        at Object.fs.readdirSync (fs.js:761:18)
        at traverse (/usr/src/app/node_modules/eslint/lib/util/traverse.js:41:12)    
        at walk (/usr/src/app/node_modules/eslint/lib/util/traverse.js:83:9)    
        at /usr/src/app/node_modules/eslint/lib/util/traverse.js:102:9
        at Array.forEach (native)
        at traverse (/usr/src/app/node_modules/eslint/lib/util/traverse.js:101:11)
        at CLIEngine.executeOnFiles (/usr/src/app/node_modules/eslint/lib/cli-engine.js:323:9)
        at Object.<anonymous> (/usr/src/app/bin/eslint:42:18)
        at Module._compile (module.js:460:26)"
```
(reformatted for easier reading)

I do not have any directory `/code` within my project, so I'm assuming this is within the docker container.

Here's my `.codeclimate.yml` file:

```yml
---
engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
ratings:
  paths:
  - "**.php"
  - "**.js"
  - "**.jsx"
  - "**.css"
exclude_paths:
- config/**/*
- spec/**/*
- tests/**/*
- node_modules/**/*
- vendor/**/*
- resources/views/**/*
- features/**/*
- database/**/*
- bootstrap/**/*
- public/**/*
- storage/**/*
- docs/**/*
- .idea/**/*
```

Unforunately I cannot provide source code for the project as it is a private codebase, but it is more-or-less the structure of a Laravel 5.0 codebase (PHP).

Please let me know if I can help debug this issue further, just wanted to report it because I know this is a young project! Thanks for releasing the engine!
