### ISSUE TITLE
Definition for rule 'import/no-extraneous-dependencies' was not found 

### ISSUE THREAD

**Issue by haines** [codeclimate/codeclimate-eslint#310]
We're running ESLint in Code Climate with a separate set of config to our main rules, because
1. we use some plugins in our main rules that aren't supported on Code Climate
2. we run ESLint in CI and fail if there are errors, so we don't need Code Climate to flag those

Our goal is just to have complexity warnings fed into Code Climate, so we have the following:

#### .codeclimate.yml:
```yml
engines:
  # ...

  eslint:
    enabled: true
    config:
      config: .codeclimate.eslintrc.json

  # ...
```

#### .codeclimate.eslintrc.json:
```json
{
  "env": {
    "node": true
  },

  "parser": "babel-eslint",

  "rules": {
    "complexity": [1, 6],
    "max-statements": [1, 20]
  }
}
```

However, Code Climate reports an error:

```
Definition for rule 'import/no-extraneous-dependencies' was not found 
```

on this line of code:

```js
const fs = require("fs");
```

It's not clear to me why the `import` ESLint plugin is getting pulled in at all, given the fairly minimal nature of .codeclimate.eslintrc.json, but we were able to fix it by disabling the check in .codeclimate.yml:

```yml
  eslint:
    enabled: true
    checks:
      import/no-extraneous-dependencies:
        enabled: false
    config:
      config: .codeclimate.eslintrc.json
```

It seems kinda strange that we needed to do this.
