### ISSUE TITLE
Add eslint-plugin-ramda to supported plugins

### ISSUE THREAD

**Issue by Undistraction** [codeclimate/codeclimate-eslint#369]
It appears that [eslint-plugin-ramda](https://github.com/ramda/) isn't currently supported and reports errors for the rules it provides. Please add it to your whitelist.

Failures 
```
Definition for rule 'ramda/always-simplification' was not found 
Definition for rule 'ramda/compose-simplification' was not found 
etc.
```

Config:

```
---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
          import/extensions:
            enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- .idea/
- docs/
- dist/
- node_modules/
- lib/
- es/
- test/
- webpack.config.js
- webpack.config-test.web.js
- jsdoc.js
```
