### ISSUE TITLE
Errors when using channel `eslint-5`

### ISSUE THREAD

**Issue by jcomplex** [codeclimate/codeclimate-eslint#434]
# Bug

## Actual Behavior
Seeing error when switching to `eslint-5` 
```
Definition for rule 'jest/prefer-spy-on' was not found
```
## Expected Behavior
No errors
## Steps to reproduce
```
engines:
  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
        import/extensions:
          enabled: false
  fixme:
    enabled: true
```
