### ISSUE TITLE
Consider upgrading prettier/eslint-config-prettier/eslint-plugin-prettier

### ISSUE THREAD

**Issue by davidkaneda** [codeclimate/codeclimate-eslint#451]
My apologies for not including steps to reproduce and such, but my repo is private and I'm just getting started with codeclimate. Essentially, I'm getting a handful of linter errors in codeclimate that I'm not locally/in Circle, and I believe it's due to the mismatch in dependencies.

My local dependencies:

```
  "devDependencies": {
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-jest": "^22.5.1",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.13.0",
    "prettier": "^1.17.0"
  }
```

Here's a sample of the errors:

![image](https://user-images.githubusercontent.com/21713/57275212-aa66be00-7052-11e9-8378-72b7836ce45b.png)

I have a sort of reverse reproduction in that if I go through and pin those 3 prettier-related deps to the versions in this repo, I get the lint errors (actually, the ones in my output plus a few more). Note that `prettier` itself actually resolves to the same version, as it hasn't had a major update like the two others.

Not sure if you have a policy on these sorts of upgrades (as I'm sure fixing for me will break others), but figured I'd give it a shot. Thanks!

**Comment by efueger** [comment]
Hi @davidkaneda ,

Can you post your .codeclimate.yml here? Happy to take a closer look. 👌 Thanks!

**Comment by davidkaneda** [comment]
Thanks, here you go:

```
plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
        - .js
        - .jsx
```

**Comment by barnholdy** [comment]
We actually have a quite similar issue.

For us `space-before-function-paren` rule seems not to be disabled by `eslint-config-prettier`.

Running this locally, gives no errors: `eslint --fix '**/*.{js,vue}'`
Whereas codeclimate fails.

Config:

`package.json`


```
"devDependencies": {
    "eslint": "^5.7.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-html-erb": "^1.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-vue": "^6.2.2",
    ...
  },
```



`.codeclimate.yml`

```
...
eslint:
    enabled: true
    channel: 'eslint-5'
    config:
      config: .eslintrc.json
      extensions:
        - .js
        - .vue
    exclude_patterns:
      - '!**/spec/'
      - '!**/test/'
```

`.eslintrc.json`

```
{
  "extends": ["eslint:recommended", "plugin:vue/essential", "plugin:prettier/recommended"],
  "rules": {
    "no-console": 1,
    "no-debugger": 0,
    "no-param-reassign": 2,    
    "vue/order-in-components": [
      "error",
      {
        "order": [
          "el",
          "name",
          "parent",
          "functional",
          ["delimiters", "comments"],
          ["components", "directives", "filters"],
          "extends",
          "mixins",
          "inheritAttrs",
          "model",
          ["props", "propsData"],
          "data",
          "computed",
          "watch",
          "LIFECYCLE_HOOKS",
          "methods",
          ["template", "render"],
          "renderError"
        ]
      }
    ],
    "vue/no-use-v-if-with-v-for": [
      "error",
      {
        "allowUsingIterationVar": true
      }
    ]
  },
  ...
}
```

@davidkaneda could you resolve the issue at your end?
@efueger any recommendations?
