### ISSUE TITLE
ESLint 5: Support `eslint-plugin-sort-keys-fix`

### ISSUE THREAD

**Issue by jcomplex** [codeclimate/codeclimate-eslint#456]
## Actual Behavior
When CodeClimate runs we receive the following error: `Module not supported: eslint-plugin-sort-keys-fix`

## Expected Behavior
CodeClimate to analyze the code correctly and return the analysis

> (1) .codeclimate.yml <br>
```
engines:
  eslint:
    enabled: true
    channel: "eslint-5"
    checks:
      import/extensions:
        enabled: false
      function-paren-newline:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_patterns:
- "assets/"
- "tests/"
- "scripts/"
- "data/"
- "/**/**/*.spec.js"
- "/**/*.spec.js"
```
