### ISSUE TITLE
Question regarding .eslintrc

### ISSUE THREAD

**Issue by Robert-W** [codeclimate/codeclimate-eslint#47]
Just a quick question for you.  Im using the codeclimate hosted service and was wondering if I need to do anything specific in my ```.codeclimate.yml``` file to tell it to use my ```.eslintrc```.  Right now my ```.codeclimate.yml``` looks like below:

```
engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- "node_modules/**"
- "www/**"
```

When using the eslint cli locally, it is pointing out some issues in the code but when I tested committing to master and reran the codeclimate analysis on the website, there aren't any issues popping up.  Am I missing something obvious here?

**Comment by dblandin** [comment]
Hey @Robert-W,

eslint should pick up an `.eslintrc` file in the root of your repository by default.

If your eslint config file is located at an alternate path, you can specify the location within your `.codeclimate.yml` file, as mentioned in our [docs](https://docs.codeclimate.com/docs/eslint#section-adding-a-eslintrc-js):

```yaml
eslint:
  enabled: true
  config:
    config: path/to/.eslintrc
```
