### ISSUE TITLE
ESLint 7 is out

### ISSUE THREAD

**Issue by chrisbutler** [codeclimate/codeclimate-eslint#490]
https://eslint.org/blog/2020/05/eslint-v7.0.0-released

Would be great to get a channel for this!

**Comment by krzysiek1507** [comment]
I guess it's done? #492

**Comment by davehenton** [comment]
@krzysiek1507 @chrisbutler the ESLint-7 channel is live!

To use the new version, update your .codeclimate.yml with the following:

```
plugins: 
  eslint:
    enabled: true
    channel: "eslint-7"
```

PS: If you have any open, erroring branches, you'll need to first make the channel change on your default branch, and then rebase any open branches on that new commit.
