### ISSUE TITLE
Can't find definitions for ember rules.

### ISSUE THREAD

**Issue by rreckonerr** [codeclimate/codeclimate-eslint#499]
# Bug Template
```js
import ActiveModelAdapter from "active-model-adapter";
```

## Actual Behavior
`Definition for rule 'ember/no-mixins' was not found.` popup is shown.
![image](https://user-images.githubusercontent.com/30495731/92257991-cdbbaa80-eede-11ea-918c-edace6eb0c38.png)

## Expected Behavior
Codeclimate should be able to read eslint rules for [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember)

## Steps to reproduce
```yml
plugins:
  eslint:
    enabled: true
    channel: "eslint-6"
```
