### ISSUE TITLE
options.extensions too limiting?

### ISSUE THREAD

**Issue by doctyper** [codeclimate/codeclimate-eslint#5]
I noticed you're limiting extensions to just `.js` files here:
https://github.com/codeclimate/codeclimate-eslint/blob/master/bin/eslint#L29

Can you make this configurable? We use `.jsx` extensions as we use React in-house. Some devs also use `.es6` as well.

**Comment by GordonDiggs** [comment]
@doctyper what would be a good pattern for you? Would setting `extensions` in your `.codeclimate.yml` work? Thinking of something like this:

```yaml
engines:
  eslint:
    enable: true
    extensions:
      - ".js"
      - ".jsx"
      - ".es6"
```
