### ISSUE TITLE
`eslint-plugin-graphql` not supported

### ISSUE THREAD

**Issue by zinkkrysty** [codeclimate/codeclimate-eslint#573]
I would have expected that the eslint graphql plugin is supported by codeclimate.

## Actual Behavior

Getting a bunch of errors in codeclimate:

> Definition for rule 'graphql/template-strings' was not found.

## Expected Behavior

The graphql plugin should work, as it does locally:

```
yarn eslint path/to/file.js

path/to/file.js
  112:22  warning  'e' is defined but never used  @typescript-eslint/no-unused-vars
  120:16  warning  'e' is defined but never used  @typescript-eslint/no-unused-vars

✖ 2 problems (0 errors, 2 warnings)

✨  Done in 4.98s.
```

## Steps to reproduce

1. Add `eslint-plugin-graphql` to package.json
2. Change configuration files:

> (1) .codeclimate.yml :
```
plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
      config: .eslintrc.json
```

> (2) .eslintrc.json :

```
  "rules": {
    "graphql/template-strings": ["error", {
      "env": "apollo"
    }]
  },
  "plugins": ["graphql"]
```
