### ISSUE TITLE
Is it possible to disable Eslint check?

### ISSUE THREAD

**Issue by josemigallas** [codeclimate/codeclimate-eslint#583]
Codeclimate is hitting OOM error during the Eslint check so we want to disable it. Even though we tried removing the entry in the yaml and settings `enabled: false` it's still running the check and failing. Is it possible to remove this check?

## Actual Behavior
Eslint check is being run

## Expected Behavior
Eslint check should be ignored

## Steps to reproduce

**codeclimate.yml**
```yml
version: 2
# All maintainability checks are enabled by default, but can be disabled or tuned individually under the checks node. Example:
# checks:
#   argument-count:
#     enabled: true
#     config:
#       threshold: 4
plugins:
  shellcheck:
    enabled: true
  brakeman:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-1-31"
  reek:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  bundler-audit:
    enabled: true
  scss-lint:
    enabled: true
exclude_patterns:
  - "**/node_modules/"
  - "**/vendor/*"
  - "app/assets/images/**/*"
  - "app/javascript"
  - "assets/bundles/*.js"
  - "bin/webpack*"
  - "cdn/*"
  - "lib/action_dispatch/rails5_ssl.rb"
  - "lib/developer_portal/app/assets/stylesheets/**/*"
  - "lib/developer_portal/app/views/developer_portal/css/*"
  - "lib/developer_portal/app/views/developer_portal/javascripts/*"
  - "public/assets"
  - "public/fancybox/*"
  - "public/images/**/*"
  - "public/javascripts/vendor/*"
  - "public/packs"
  - "public/themes/**/*"
  - "spec/**/*"
  - "spec/**/**/*"
  - "test/**/*"
  - "tmp/**/*"
```

## Relevant links
https://github.com/3scale/porta/pull/3104
https://codeclimate.com/github/3scale/porta/pull/3104
