### ISSUE TITLE
Error on Analysis Configuration .codeclimate.yml

### ISSUE THREAD

**Issue by Adebesin-Cell** [codeclimate/codeclimate-eslint#585]
# Bug Template

## Actual Behavior
We are left with only one error with eslint-7 after the support recommendation through mail.

<img width="1081" alt="CleanShot 2023-02-08 at 19 06 06@2x" src="https://user-images.githubusercontent.com/52039218/217545533-db99a6b8-2485-46f6-853b-37af46ae00cd.png">

So we are using `eslint-plugin-unused-imports` plugin for checking unused imports which i believe is not yet supported on code climate. 

<img width="800" alt="CleanShot 2023-02-08 at 19 07 22@2x" src="https://user-images.githubusercontent.com/52039218/217545523-881dc8cc-ccbe-40f0-a617-f640d7c26ee0.png">

They are only checking with specific es lint versions and only with few subset of available eslint plugins

<img width="841" alt="CleanShot 2023-02-08 at 19 05 53@2x" src="https://user-images.githubusercontent.com/52039218/217545550-33e3cd5d-1031-4b27-8d88-0d14890dc7b1.png">

We checked the github repo from code climate but not able to find the plugin in their package json - https://github.com/codeclimate/codeclimate-eslint/blob/channel/eslint-7/package.json

<img width="1059" alt="CleanShot 2023-02-08 at 19 07 06@2x" src="https://user-images.githubusercontent.com/52039218/217545530-e1bdc6ab-3ca2-4ff9-abd8-810e21ba77e7.png">

## Expected Behavior
Successful github checks

## Steps to reproduce

```
version: '2' # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 30
  identical-code:
    enabled: true
    config:
      threshold: 50

plugins:
  eslint:
    enabled: true
    channel: 'eslint-7'

exclude_patterns:
  - 'config/'
  - 'db/'
  - 'dist/'
  - 'features/'
  - '**/node_modules/'
  - 'script/'
  - '**/spec/'
  - '**/test/'
  - '**/tests/'
  - 'Tests/'
  - '**/vendor/'
  - '**/*_test.go'
  - '**/*.d.ts'
```

## Relevant links

https://codeclimate.com/github/EveripediaNetwork/ep-ui/pull/1137

----
- [ ] 4-6 word issue title
