### ISSUE TITLE
eslint2 doesn't pick up custom js config file

### ISSUE THREAD

**Issue by sagiegurari** [codeclimate/codeclimate-eslint#94]
check example repo: https://github.com/sagiegurari/simple-oracledb
codeclimate yml: https://github.com/sagiegurari/simple-oracledb/blob/master/.codeclimate.yml
.eslintrc.js (not .eslintrc): https://github.com/sagiegurari/simple-oracledb/blob/master/.eslintrc.js

in yml I got:
````yml
eslint:
    enabled: true
    channel: "eslint-2"
    config:
      config: .eslintrc.js
````

but after codeclimate build, i get a warning that some config was auto generated and I see it generated .eslintrc for some reason.

https://codeclimate.com/repos/561f3da769568023050054c3/analysis_config
